In [1]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd

In [2]:
x = [8.0, 1, 2.5, 4, 28.0]

In [3]:
x_with_nan = [8.0, 1, 2.5, math.nan, 4, 28.0]

In [4]:
y, y_with_nan = np.array(x), np.array(x_with_nan)
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)

#### Measures of Central Tendency
Mean

Weighted mean

Geometric mean

Harmonic mean

Median

Mode

In [27]:
y.mean()

8.7

In [28]:
np.mean(y)

8.7

In [29]:
np.mean(y_with_nan)

nan

In [30]:
np.nanmean(y_with_nan)

8.7

In [31]:
w = [0.1, 0.2, 0.3, 0.25, 0.15]


In [32]:
wmean = np.average(y , weights = w)

In [33]:
wmean

6.95

In [3]:
import scipy.stats as stats

In [35]:
stats.gmean(y)           #array

4.67788567485604

In [36]:
stats.gmean(z)                 #Series

4.67788567485604

In [37]:
stats.gmean(y_with_nan)

nan

In [38]:
stats.hmean(z)  

2.7613412228796843

In [39]:
stats.hmean(y_with_nan)

C:\Users\BARAKHA\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy\stats\stats.py:370: RuntimeWarning: invalid value encountered in greater
  if np.all(a > 0):


ValueError: Harmonic mean only defined if all elements greater than zero

In [40]:
np.median(x)

4.0

In [41]:
np.median(x_with_nan)

nan

In [42]:
np.nanmedian(x_with_nan)

4.0

In [5]:
v = [12, 15, 12, 15, 21, 15, 12]

In [6]:
mode_ = scipy.stats.mode(v)
mode_

ModeResult(mode=array([12]), count=array([3]))

In [7]:
mode_.mode


array([12])

In [8]:

mode_.count

array([3])

In [46]:
v = pd.Series(v)
v.mode()          #Second way

0    12
1    15
dtype: int64

In [44]:
v.mode()[0]

12

In [45]:
v.mode()[1]

15

#### Measures of Variability
Variance

Standard deviation

Skewness

Percentiles

Ranges

In [13]:
#pd.Series objects have the method .var() that skips nan values by default

In [14]:
 z.var(ddof=1)

123.19999999999999

In [15]:
z_with_nan.var(ddof=1)

123.19999999999999

In [16]:
np.std(y_with_nan, ddof=1)  #array

nan

In [17]:
y_with_nan.std(ddof=1) #array

nan

In [18]:
#Skewness

In [19]:
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)
z.skew()

1.9470432273905924

In [20]:
z_with_nan.skew()

1.9470432273905924

In [21]:
#percentile() takes several arguments. 
#You have to provide the dataset as the first argument and the percentile value as the second. 
#The dataset can be in the form of a NumPy array, list, tuple, or similar data structure. 
#The percentile can be a number between 0 and 100  
#but it can also be a sequence of numbers:

In [23]:
y = np.array(x)
np.percentile(y, 5)

1.3

In [22]:
np.percentile(y, [25, 50, 75])

array([2.5, 4. , 8. ])

NumPy also offers you very similar functionality in quantile() and nanquantile(). If you use them, then you’ll need to provide the quantile values as the numbers between 0 and 1 instead of percentiles:

In [24]:

np.quantile(y, 0.95)




23.999999999999996

In [25]:
np.quantile(y, [0.25, 0.5, 0.75])



array([2.5, 4. , 8. ])

In [26]:
np.nanquantile(y_with_nan, [0.25, 0.5, 0.75])

array([2.5, 4. , 8. ])

The range of data is the difference between the maximum and minimum element in the dataset.