In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as stats
%matplotlib inline
import seaborn as sns

In [2]:
stats.chi2.isf(0.05,2)

5.991464547107983

In [3]:
stats.chi2.isf(0.05,7)

14.067140449340167

In [5]:
2*(1-stats.norm.cdf(-0.96))

1.6629447850663244

In [6]:
table = np.array([10,15,25,10,20,20]).reshape(2,3)
table

array([[10, 15, 25],
       [10, 20, 20]])

In [7]:
stats.chi2_contingency(table)

(1.2698412698412698,
 0.5299775483586844,
 2,
 array([[10. , 17.5, 22.5],
        [10. , 17.5, 22.5]]))

In [8]:
# Test of goodness of fit
obs = np.array([22,21,19,20,18])
exp = np.array([20,20,20,20,20])
stats.chisquare(obs,exp)

Power_divergenceResult(statistic=0.5, pvalue=0.9735009788392561)

In [10]:
#test of variance
ar = np.array([172,156,154,163,170,169,170,164])
n = len(ar)
s2 = np.var(ar, ddof = 1)
chistat = (n*s2)/4 #sigma**2 = 4
chistat


pval = stats.chi2.sf(chistat,n-1)
pval

chicrit = stats.chi2.isf(0.05,n-1)
chicrit
print(chistat,chicrit,pval)

91.85714285714286 14.067140449340167 5.138829182841623e-17


In [11]:
#Refer to the above example 5. Here the operations manager changes his belief and now believes that 28% of their passengers prefer vegan food, 42% prefer vegetarian food , 25% prefer non-veg food 5% request for Jain food.

#At 5% level of significance, can you confirm that the meal preference is as per the belief of the operations manager?

In [13]:
observed_values    = np.array([190, 185, 90, 35])
n                  = observed_values.sum()

expected_values    = np.array([n*0.28, n*.42, n*0.25, n*0.05])

In [14]:
# H0 : operations managers belief holds good
# H1 : operations managers belief not holds good
stats.chisquare(observed_values,expected_values)

Power_divergenceResult(statistic=34.63333333333334, pvalue=1.4561004918754443e-07)

In [17]:
#A Cable service provider company is interested in checking whether or not the customer churn depends on customer segment. Use 5% as level of significance
# H0: the customer churn doesn't depend on customer segment.
# H1: the customer churn depends on customer segment

In [16]:
churn_array = np.array([[15,142],[24, 400],[30, 389]])
stats.chi2_contingency(churn_array)

(2.779977047087869,
 0.24907816314986156,
 2,
 array([[ 10.833, 146.167],
        [ 29.256, 394.744],
        [ 28.911, 390.089]]))